language: ruby
rvm:
- 2.2.2
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key: da24db08-47b7-408c-8550-9df85119c56c
  app: auto-biography
  on:
    branch: development
script:
- bundle exec rake db:drop
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake
